### PR TITLE
Fix for Long Startup Time

### PR DESCRIPTION
**Pull request by pradeepjairamani**
#### Checklist
- [x] I have followed the [Contributor Guidelines](https://github.com/zdresearch/OWASP-Nettacker/wiki/Developers#contribution-guidelines).
- [x] I have added the relevant documentation.
- [x] My branch is up-to-date with the Upstream master branch.

#### Changes proposed in this pull request

Fix Issue #163 

#### Your development environment
- OS: `Kali Linux`
- OS Version: `2.0`
- Python Version: `2.7.3`

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
any thoughts? @pradeepjairamani @shaddygarg

**Comment by shaddygarg** [comment]
I think it is a good idea to do this!!

**Comment by pradeepjairamani** [comment]
That is a good idea..

**Comment by Ali-Razmjoo** [comment]
so @pradeepjairamani please work on this one.

**Comment by pradeepjairamani** [comment]
I tried doing the timeout thing using request but It didn't worked. Let me see if I can find anything else

**Comment by Ali-Razmjoo** [comment]
do you mean this?! working fine for me! 
```python
In [25]: def a(timeout):
    ...:     try:
    ...:         requests.get("http://api.z3r0d4y.com:810/", timeout=timeout)
    ...:     except:
    ...:         pass
    ...:

In [26]: %time a(None)
Wall time: 42.2 s

In [27]: %time a(1)
Wall time: 2 s

In [28]: %time a(3)
Wall time: 6 s
```

anyway after setting the timeout, if you implement the database thing it would be not a problem, 42sec in 24 hours will not count as anything :D! 

Regards.

**Pull request closed without merging**
