### PR TITLE
Improved X-XSS-Protection header codebase

### PR DESCRIPTION
**Pull request by aman566**
Added two different parameters that may also be present in some websites while checking for X-XSS-Protection header. Used regex for report-uri parameter in the header.

#### Checklist
- [X] I have followed the [Contributor Guidelines](https://github.com/zdresearch/OWASP-Nettacker/wiki/Developers#contribution-guidelines).
- [X] I have added the relevant documentation.
- [X] My branch is up-to-date with the Upstream master branch.

#### Your development environment
- OS: `Linux`
- OS Version: `Ubuntu`
- Python Version: `3.6.9`

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ lib/vuln/XSS_protection/engine.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/zdresearch/OWASP-Nettacker/pullRequest?prid=5173434&bid=16982579)

**Comment by Ali-Razmjoo** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ lib/vuln/XSS_protection/engine.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/zdresearch/OWASP-Nettacker/pullRequest?prid=5173434&bid=16982579)

**Comment by shaddygarg** [comment]
@Ali-Razmjoo, this seems alright, We can merge it.

**Comment by Ali-Razmjoo** [comment]
Hi, thanks for the PR, merged.

**Pull request merged**
