### PR TITLE
Add services and regex matching to the service scanner

### PR DESCRIPTION
**Pull request by shaddygarg**
#### Checklist
- [x] I have followed the [Contributor Guidelines](https://github.com/zdresearch/OWASP-Nettacker/wiki/Developers#contribution-guidelines).
- [x] I have added the relevant documentation.
- [x] My branch is up-to-date with the Upstream master branch.

#### Changes proposed in this pull request
I have added some more signatures to the service scanner and a new component which uses regex matching to scan for services.

#### Your development environment
- OS: `Ubuntu`
- OS Version: `16.04`
- Python Version: `2.7.12`

### CODE REVIEW

**Comment by shaddygarg** [comment]
This is in reference to issue #152

**Comment by shaddygarg** [comment]
If someone wants to add a new regex, make sure it is tested. You can use https://regexr.com/ for seeing if your regex's are valid or not otherwise they will be ignored

**Comment by Ali-Razmjoo** [comment]
@shaddygarg  thanks for the contribution, please prepare documentation for wiki while I'm reviewing.

regards.

**Comment by Ali-Razmjoo** [comment]
@pradeepjairamani please review @shaddygarg's code regarding this PR and confirm if it's ready to merge.

**Comment by Ali-Razmjoo** [comment]
@pradeepjairamani thanks for the review, @shaddygarg thanks for the contribution, PR merged.

**Pull request merged**
