### PR TITLE
Complete the tutorial using introJs for WebView

### PR DESCRIPTION
**Pull request by shaddygarg**
#### Checklist
- [x] I have followed the [Contributor Guidelines](https://github.com/zdresearch/OWASP-Nettacker/wiki/Developers#contribution-guidelines).
- [x] I have added the relevant documentation.
- [x] My branch is up-to-date with the Upstream master branch.

#### Changes proposed in this pull request
This is a pull request that adds the tutorial made using introJS for the web view in reference to the issue #132 . Here are some screenshots.  
image  
image
image
Please let me know about any changes that you want in this tutorial.
#### Your development environment
- OS: `Ubuntu`
- OS Version: `16.04`
- Browser: `Firefox Quantum 60.0.2`

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
Hi shaddy,

thanks for  your contribution, it needs a little bit fixation for button and texts colors, it's kind of not cool, I've tried to change them but I am not a good UI developer to decide ... can you send a few updates regarding the colors and UI?

Regards.

**Comment by shaddygarg** [comment]
@Ali-Razmjoo, Here is a link for some custom themes https://introjs.com/docs/themes/list. Please check if any of them looks good. I was in a dilemma regarding which theme to use.

**Comment by Ali-Razmjoo** [comment]
@shaddy this modern theme looks good. https://introjs.com/docs/themes/list#modern

**Comment by shaddygarg** [comment]
I have applied the modern theme. Here are some of the screenshots!
image
image
image

**Comment by Ali-Razmjoo** [comment]
Hi,

thanks for your contribution, PR merged.

best regards.

**Pull request merged**
