### PR TITLE
Requirements updated with version

### PR DESCRIPTION
**Pull request by pradeepjairamani**
Describe your changes or your new module and let us know which OS and Python version you tested on.
_________________
**OS**: `Ubuntu`

**OS Version**: `16.04`

**Python Version**: `2.7.3`

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
Hey,

I recently added the automated code coverage sending to codacy, the environment variable `CODACY_PROJECT_TOKEN` exist already and I've sent some commits, that's weird! let me check to find the problem.

BTW, shouldn't we use the latest version of the modules instead of defining the version? what's your point?

Regards.

**Comment by Ali-Razmjoo** [comment]
Hey,

Pyup is commercial for organizations, I think if users use `--upgrade` switch it will be installing the latest version, but it's some kind better for virtualenv, so let's merge it!

Regards.

**Comment by pradeepjairamani** [comment]
Hello,

I have installed and tested pyup for the fork of Nettacker and it is free for public repositories, we can implement it.

Best Regards

**Comment by Ali-Razmjoo** [comment]
Hey,

maybe you can monitor it and send the PR, but because it's on your github "user" not organization, you can use pyup for free.

Regards.

**Comment by pradeepjairamani** [comment]
Sure I will monitor and send the PR

Best Regards

**Pull request merged**
