### PR TITLE
Now http://website.com  as well as http://website.com/  both are recognized by nettacker correctoly and no error comes.

### PR DESCRIPTION
**Pull request by VictorSuraj**
…gnized by nettacker correctoly.

Describe your changes or your new module and let us know which OS and Python version you tested on.
_________________
**OS**: 'Linux' or 'Windows'

**OS Version**: `x`

**Python Version**: `2.7`

### CODE REVIEW

**Comment by Ali-Razmjoo** [comment]
Hello,

Thank you. PR merged.

Best Regards.

**Comment by VictorSuraj** [comment]
Actually sir, I want to say you thanks because of this open source teach me a lot in python.

**Comment by VictorSuraj** [comment]
hello sir,  Currently I add a patc

*h in OWASP-Nettacker
<https://github.com/VictorSuraj/OWASP-Nettacker/tree/4390444be664596cedbda1893e3bd45b02f1c92d>/lib
<https://github.com/VictorSuraj/OWASP-Nettacker/tree/4390444be664596cedbda1893e3bd45b02f1c92d/lib>/scan
<https://github.com/VictorSuraj/OWASP-Nettacker/tree/4390444be664596cedbda1893e3bd45b02f1c92d/lib/scan>/port
<https://github.com/VictorSuraj/OWASP-Nettacker/tree/4390444be664596cedbda1893e3bd45b02f1c92d/lib/scan/port>/engine.py
but this was not added in branch.  I want please check and review the code.*



*I add this patch because of, for  some rare website  like amazon.com
<http://amazon.com> port 0 is well managed and our code is not working
properly their to bring all filterd port but currently it is working for
all.*

*Thank youVictorSuraj*

**Comment by Ali-Razmjoo** [comment]
Hey @VictorSuraj,

Please send a new PR, I will guide and review your code. it could be edited there.

Regards.

**Pull request merged**
